version: '3.9'
services:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: api.Dockerfile
    logging:
      driver: "none"
    ports:
      - "3333:3333"

  cypress:
    container_name: cypress
    environment:
      - ELECTRON_ENABLE_LOGGING=false
    depends_on:
      - "backend"
    build:
      context: ./
      dockerfile: ./app.Dockerfile
    volumes:
      - type: bind
        source: ./cy-output
        target: /client/dist
    ports:
      - "4200:4200"
